mysite/mysite/gview/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'gview'

urlpatterns = [
    path('',  TemplateView.as_view(template_name='gview/main.html')),
    path('cats', views.CatListView.as_view(), name='cats'),
    path('cat/<int:pk_from_url>', views.CatDetailView.as_view(), name='cat'),
    # path('dogs', views.DogListView.as_view(), name='dogs'),
    # path('dog/<int:pk_from_url>', views.DogDetailView.as_view(), name='dog'),
]

mysite/mysite/home/urls.py
from django.urls import path, include
from . import views
# from django.views.generic.base import TemplateView

urlpatterns = [
    path('danger/', views.danger),
    path('rest/<int:guess>', views.guessing),
    path('bounce', views.bounce),
    path('', views.home),
    # path('main', TemplateView.as_view(template_name='home/main.html')),
]

mysite/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from page import views
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home/', include('home.urls')),
    path('home/', include('home.urls')),
    path('page/', views.lessons),
    path('bounce/', views.bounce),
    path('tmpl/', include('tmpl.urls')),
    path('route/', include('route.urls')),
    path('gview/', include('gview.urls')),
    path('getpost/', include('getpost.urls')),
    path('session/', include('session.urls')),
    path('authz/', include('authz.urls')),
    path('', TemplateView.as_view(template_name='base.html')),
]

mysite/mysite/gview/models.py
from django.db import models

# Create your models here.
class Cat(models.Model):
    name = models.CharField(max_length=128)


class Dog(models.Model):
    name = models.CharField(max_length=128)


class Horse(models.Model):
    name = models.CharField(max_length=128)


class Car(models.Model):
    name = models.CharField(max_length=128)

mysite/mysite/gview/views.py
from django.shortcuts import render
from django.views import View
from django.views import generic

from gview.models import Cat, Dog, Horse, Car

# Create your views here.

class CatListView(View):
    def get(self, request):
        stuff = Cat.objects.all()
        cntx = { 'cat_list': stuff }
        return render(request, 'gview/cat_list.html', cntx)


class CatDetailView(View):
    def get(self, request, pk_from_url):
        obj = Cat.objects.get(id=pk_from_url)
        cntx = { 'cat': obj }
        return render(request, 'gview/cat_detail.html', cntx)


class DogListView(View):
    model = Dog
    def get(self, request):
        modelname = self.model._meta.varbose_name.title().lower()
        stuff = self.model.objects.all()
        cntx = { modelname+'_list': stuff }
        return render(request, 'gview/'+modelname+'_list.html', cntx)


class DogDetailView(View):
    model = Dog
    def get(self, request):
        modelname = self.model._meta.varbose_name.title().lower()
        stuff = self.model.objects.all()
        cntx = { modelname : obj }
        return render(request, 'gview/'+modelname+'_detail.html', cntx)


class HorseListView(generic.ListView):
    # extends DogListView
    model = Horse


class SampleListView(View):
    def get(self, sequest):
        modelname = self.model._meta.varbose_name.title().lower()
        stuff = self.model.objects.all()
        cntx = { modelname+'_list': stuff }
        return render(request, 'gview/'+modelname+'_list.html', cntx)


class CarListView(SampleListView):
    # Has the same syntax as HorseListView
    model = Car


class CarDetailView(SampleListView):
    model = Car

mysite/mysite/gview/templates/gview/cat_detail.html
{% extends "base.html" %}

{% block title %}Data Center{% endblock title %}

{% block content %}
<h1>Cat {{ cat.name }}</h1>
<p><a href="{% url 'gview:cats' %}">Go back</a></p>
{% endblock content %}

mysite/mysite/gview/templates/gview/cat_list.html
{% extends "base.html" %}

{% block title %}Data Center{% endblock title %}

{% block content %}
<h1>Cats</h1>
{% if cat_list is not None %}
  <ul>
    {% for obj in cat_list %}
      <li><a href="{% url 'gview:cat' obj.id %}">{{ obj.name }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>There is no cats in the database</p>
{% endif %}
{% endblock content %}

mysite/mysite/gview/templates/gview/main.html
{% extends "base.html" %}

{% block title %}Data Center{% endblock title %}

{% block content %}
<ul>
  <li><a href="{% url 'gview:cats' %}">A list of cats</a></li>
  <li><a href="{% url 'gview:dogs' %}">A list of cats</a></li>
</ul>
{% endblock content %}